import {
  Activity,
  BookOpen,
  Bot,
  BrainCircuit,
  Cpu,
  Database,
  Globe,
  HardDrive,
  Home,
  Languages,
  LayoutDashboard,
  LogOut,
  MemoryStick,
  Moon,
  Network,
  Palette,
  RefreshCw,
  Send,
  Server,
  ShieldCheck,
  Sparkles,
  User,
  Boxes,
  Wrench,
  Cable,
  Workflow,
  Building2,
} from 'lucide-react';

/**
 * ZRH Design System — 图标注册表（统一 Lucide 来源，禁止散引）
 */
export const zrhIcons = {
  brand: Sparkles,
  globe: Globe,
  ai: BrainCircuit,
  home: Home,
  dashboard: LayoutDashboard,
  cpu: Cpu,
  gpu: BrainCircuit,
  memory: MemoryStick,
  disk: HardDrive,
  network: Network,
  database: Database,
  redis: Server,
  docker: Boxes,
  activity: Activity,
  user: User,
  logout: LogOut,
  language: Languages,
  theme: Palette,
  dark: Moon,
  shield: ShieldCheck,
  send: Send,
  refresh: RefreshCw,
  knowledge: BookOpen,
  rag: BrainCircuit,
  agents: Bot,
  tools: Wrench,
  mcp: Cable,
  workflows: Workflow,
  business: Building2,
} as const;

export type ZrhIconName = keyof typeof zrhIcons;
